<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Constancia de Ingreso</title>
    <head>
        <style>
           <head>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            position: relative;
        }

        /* Fondo repetido para la marca de agua */
        body::before {
            content: "INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO";
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            color: yellow; /* Color del texto */
            font-size: 14px; /* Tamaño pequeño de texto */
            font-weight: bold;
            opacity: 0.1; /* Transparencia tenue */
            z-index: -1; /* Debajo del contenido principal */
            white-space: nowrap; /* Sin saltos de línea */
            overflow: hidden;
            pointer-events: none; /* No interactúa con clics */
            background: repeating-linear-gradient(
                0deg, /* Horizontal */
                yellow 0, 
                yellow 250px, /* Ancho entre repeticiones */
                transparent 250px, 
                transparent 260px /* Separación */
            );
            line-height: 40px; /* Ajusta la separación entre texto */
        }

        .container {
            width: 80%;
            margin: auto;
            padding: 20px;
            position: relative;
        }

        .title {
            text-align: center;
            font-size: 18px;
            font-weight: bold;
            margin-top: 20px;
            margin-bottom: 20px;
        }

        .content {
            font-size: 14px;
            line-height: 1.6;
            border: 1px solid #000;
            padding: 20px;
            border-radius: 15px;
            margin-top: 20px;
        }

        .footer {
            text-align: center;
            margin-top: 30px;
        }

        #titulo_constancia {
            text-align: center;
            font-size: 20px;
            font-weight: bold;
            color: white;
            background-color: #2c3e50;
            padding: 4px;
            border: 2px solid black;
            border-radius: 5px;
        }
    </style>
</head>

    </head>
    
</head>
<body>
    <div style="position: relative;">
        <!-- Marca de agua -->
        <div style="
           position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: -1; /* Detrás del contenido principal */
    pointer-events: none; /* No interferir con clics o elementos interactivos */
    font-size: 9px; /* Tamaño del texto */
    font-weight: bold;
    color: yellow; /* Texto amarillo */
    opacity: 0.5; /* Transparencia */
    background: repeating-linear-gradient(
        0deg, 
        yellow 0, 
        yellow 20px, 
        transparent 20px, 
        transparent 40px
    );
    background-size: cover; /* Asegura que cubre todo el área */
          
        ">
            <!-- Repetimos varias líneas del texto -->
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO 
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO 
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO 
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
            INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO PÚBLICO GAMANIEL BLANCO MURILLO
           
        </div>
        
            
    <div class="container">
        <div style="text-align: center; margin-bottom: 20px;">
            <img id="logocabecera" src="{{public_path('logos/cabecera.jpg')}}" alt="Cabecera" style="width: 100%; max-width: 600px; height: auto;">
        </div>

        <!-- Logo (debajo de la cabecera) -->
        <div style="text-align: center; margin-bottom: 10px;">
            <img id="logogamaniel" src="{{public_path('logos/logo.png')}}" alt="Logo Gamaniel" style="width: 120px; height: auto;">
        </div>
        <div class="title" style="margin: 0;">
            ESCUELA DE EDUCACIÓN SUPERIOR PEDAGÓGICA PÚBLICA<br>"GAMANIEL BLANCO MURILLO"
        </div>
        <center><p style="margin: 0; font-size: 12px;"><strong>R.M. Nº:</strong> 0205-81-ED - 18-03-1981</p></center>
        <center><p>Institución Innovadora Formando Docentes Líderes, Competitivos, Acreditados y Rumbo al Licenciamiento.</p></center>
        <h2 id="titulo_constancia">CONSTANCIA DE INGRESO</h2>
        <div class="content"> <!-- Borde comienza aquí -->
            @foreach ($datosconstanciaingre as $item)
            <p>El Director de la Escuela de Educación Superior Pedagógica Pública "Gamaniel Blanco Murillo" de Cerro de Pasco; CERTIFICA que de acuerdo al Padrón de Resultados del PROCESO DE {{$item->nombre_proceso}}, el siguiente postulante ingresó a nuestra Casa Superior de Estudios:</p>
                <table>
                    <tr>
                        <td><strong>PROGRAMA DE ESTUDIOS:</strong></td>
                        <td>{{$item->nombre_de_carrera}}</td>
                    </tr>
                    <tr>
                        <td><strong>APELLIDO PATERNO:</strong></td>
                        <td>{{$item->apellidos_pater_postulante}}</td>
                    </tr>
                    <tr>
                        <td><strong>APELLIDO MATERNO:</strong></td>
                        <td>{{$item->apellidos_mater_postulante}}</td>
                    </tr>
                    <tr>
                        <td><strong>NOMBRES:</strong> </td>
                        <td>{{$item->nombres_postulante}}</td>
                    </tr>
                    <tr>
                        <td><strong>MODALIDAD DE INGRESO:</strong></td>
                        <td>{{$item->nombre_modalidad}}</td>
                    </tr>
                    <tr>
                        <td><strong>PUNTAJE:</strong></td>
                        <td> {{$item->nota_total}}</td>
                    </tr>
                    <tr>
                        <td><strong>ORDEN DE MÉRITO:</strong></td>
                        <td>{{$item->orden_de_merito}}</td>
                    </tr>
                    <tr>
                        <td><strong>CÓDIGO DE MATRÍCULA:</strong></td>
                        <td>{{$item->idpostulante}}</td>
                    </tr>

                </table>
           
            @endforeach
            <p style="text-align:right;">
                Cerro de Pasco, 
                <?php 
                    setlocale(LC_TIME, 'es_ES.UTF-8'); // Configurar el idioma en español
                    echo strftime('%d de %B del %Y'); // Formato: "12 de marzo del 2025"
                ?>
            </p>
            
        </div> <!-- Borde termina aquí -->
        <div class="footer">
            <p>__________________________</p>
            <p><strong>Firma del Director</strong></p>
            <p>Mg. Luis Ricardo Espinoza</p>
        </div>
    </div>
</body>
</html>
